version: '2'
services:
  work:
    build: ./docker
    command: jupyter lab --allow-root --ip 0.0.0.0 --port 8888
    ports:
      - "8888:8888" # Jupyter Notebook
    volumes:
      - .:/root/work
      - ../dataStore_upconversion:/root/dataStore_upconversion
      
